In [1]:
import tensorflow as tf

C:\Users\varun\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\varun\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\varun\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\varun\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passi

In [2]:
hello = tf.constant("Hello ")

In [3]:
world = tf.constant("World")

In [4]:
print(hello) # TRYING TO PRINT THE STRING PRESENT IN THE VARIABLE # 

Tensor("Const:0", shape=(), dtype=string)


In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

* AS THE STRING IS DEFINED INSIDE A TENSORFLOW FRAMEWORK WE NEED TO CREATE SESSION TO PRINT IT.

In [6]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [7]:
print(result)

b'Hello World'


In [8]:
a = tf.constant(10)

In [9]:
b = tf.constant(20)

In [10]:
type(a)

tensorflow.python.framework.ops.Tensor

In [11]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [12]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [13]:
print(result)

30


* WE NEED TO CREATE A SESSION INORDER TO PRINT THE RESULT OF TENSORFLOW

In [14]:
const = tf.constant(10)

In [15]:
fill_mat = tf.fill((4,4), 10)

In [16]:
myzeros = tf.zeros((4,4))

In [17]:
myones = tf.ones((4,4))

In [18]:
myrand = tf.random_normal((4,4), mean = 0, stddev = 1.0)

In [19]:
myrandu = tf.random_uniform((4,4), minval = 0, maxval = 1)

In [20]:
my_ops = [const, fill_mat, myzeros, myones, myrand, myrandu]

In [21]:
sess = tf.InteractiveSession() # ANOTHER TYPE OF SESSION IN TENSOR FLOW TO PRINT THE RESULTS. THIS IS USED ONLY IN JUPYTER NOTEBOOK #

In [22]:
for op in my_ops:
   print(sess.run(op))
   print()

10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[ 0.49806553  0.37058085 -1.0062479  -0.09357777]
 [-0.44965696  0.840218   -0.05946507  1.1880714 ]
 [ 0.37827787 -0.39379784 -1.4672765   0.14612894]
 [ 0.30768505  0.60759485 -1.4533323   1.500717  ]]

[[0.5526378  0.6740571  0.26053286 0.8021685 ]
 [0.8141066  0.8677547  0.89328575 0.26429355]
 [0.0279851  0.35828853 0.63626313 0.29650748]
 [0.5492374  0.24874151 0.6191274  0.3681376 ]]



* IN THE ABOVE OPERATION WE JUST CALLED THE SESSION INTERACTIVE NAME AND THE PROCESS IS CARRIED AS SIMILAR AS THE "tf.session"

In [23]:
a = tf.constant([[1,2],[3,4]])

In [24]:
a.get_shape() # HELPS IN PRINTING THE MATRIX CONFIGURATION #

TensorShape([Dimension(2), Dimension(2)])

In [25]:
b = tf.constant([[10], [100]])

In [26]:
result = tf.matmul(a,b)

In [27]:
sess.run(result)

array([[210],
       [430]])

* THE ABOVE SESSION IS RUN  BY THE INTERACTIVE SESSION LIBRARY.

# TENSORFLOW GRAPHS